// キャラクター定義（54人）
// face: 0=文豪列伝(Front), 1=闇の系譜(Back), 2=女性の先駆者(Right),
//        3=西洋の魂(Left), 4=芸術家・詩人(Top), 5=異界の存在(Bottom)

export const INITIAL_CHARACTERS = [
  // ── Face 0: 文豪列伝 ──────────────────────────────────────────────
  { id: 'soseki', face: 0, pos: 0, name: '夏目漱石', role: '大学教授', homeLocationId: 'school', flavor: '胃痛', color: 'bg-itako-clay', isMainChar: true, description: '日本の小説家、英文学者。大学教授としての職務と創作の狭間で胃を病んでいる。', avatar: 'assets/soseki_warhol.webp', isPreStyled: true },
  { id: 'ogai', face: 0, pos: 1, name: '森鴎外', role: '軍医・文豪', homeLocationId: 'library', flavor: '知性', color: 'bg-zinc-700', description: '軍医でありながら文学を愛し、近代と伝統の狭間で二重生活を送った。', avatar: null },
  { id: 'akutagawa', face: 0, pos: 2, name: '芥川龍之介', role: '鬼才作家', homeLocationId: 'mirror', flavor: '不安', color: 'bg-red-950/50', description: '鋭敏な感受性と知性、そして「薄ぼんやりした不安」に追われ続けた天才。', avatar: null },
  { id: 'dazai', face: 0, pos: 3, name: '太宰治', role: '恥の多い生涯', homeLocationId: 'canal', flavor: '失格', color: 'bg-zinc-800', description: '人間失格を自称しながら、それでも言葉で世界と戦い続けた魂。', avatar: null },
  { id: 'mishima', face: 0, pos: 4, name: '三島由紀夫', role: '作家・武人', homeLocationId: 'roof', flavor: '美と死', color: 'bg-red-900/60', description: '美への執着と肉体の鍛錬、そして壮絶な最期まで自らを物語の主人公とした。', avatar: null },
  { id: 'kawabata', face: 0, pos: 5, name: '川端康成', role: 'ノーベル賞作家', homeLocationId: 'garden', flavor: '余韻', color: 'bg-itako-sage', description: '雪国の純白の中に、消えゆくものへの哀愁を刻んだ。', avatar: null },
  { id: 'kafuka', face: 0, pos: 6, name: 'カフカ', role: '保険局員・作家', homeLocationId: 'waiting', flavor: '変身', color: 'bg-zinc-700', description: '虫になった男と不条理な城を描いた、実存の悪夢の語り手。', avatar: null },
  { id: 'borges', face: 0, pos: 7, name: 'ボルヘス', role: '図書館司書', homeLocationId: 'archive', flavor: '迷宮', color: 'bg-itako-sand', description: '無限の図書館と砂の本を夢想した、盲目の宇宙論者。', avatar: null },
  { id: 'k_kokoro', face: 0, pos: 8, name: 'K', role: '無職・書生', homeLocationId: 'stair', flavor: '絶望', color: 'bg-zinc-800', isMainChar: true, description: 'かつては学生。今はただ絶望の螺旋階段を上り下りする、目的を持たない魂。', avatar: null },

  // ── Face 1: 闇の系譜 ──────────────────────────────────────────────
  { id: 'dosto', face: 1, pos: 0, name: 'ドストエフスキー', role: '債務者・作家', homeLocationId: 'casino', flavor: '借金', color: 'bg-itako-sand', isMainChar: true, description: 'ロシアの文豪。ルーレットへの執着と膨大な借金、そして信仰の間で魂が微振動している。', avatar: 'assets/dosto_warhol.webp', isPreStyled: true },
  { id: 'nietzsche', face: 1, pos: 1, name: 'ニーチェ', role: '反哲学者', homeLocationId: 'monolith', flavor: '超人', color: 'bg-zinc-700', description: '神は死んだ。超人の到来を高らかに宣言したが、自身は錯乱の闇に消えた。', avatar: null },
  { id: 'poe', face: 1, pos: 2, name: 'エドガー・アラン・ポー', role: '幻想作家', homeLocationId: 'box', flavor: '奈落', color: 'bg-zinc-800', description: '黒猫と大鴉に囲まれ、酒と死と美の幻想を紡いだ。', avatar: null },
  { id: 'marquis', face: 1, pos: 3, name: 'サド侯爵', role: '囚人・作家', homeLocationId: 'prison', flavor: '快楽', color: 'bg-red-950/60', description: '監獄の闇の中で最も過激な思想を書き続けた。', avatar: null },
  { id: 'baudelaire', face: 1, pos: 4, name: 'ボードレール', role: '呪われた詩人', homeLocationId: 'backalley', flavor: '悪の華', color: 'bg-zinc-700', description: '悪と美を同一視した詩人。梅毒と貧困の中で近代詩を発明した。', avatar: null },
  { id: 'rimbaud', face: 1, pos: 5, name: 'ランボー', role: '天才少年詩人', homeLocationId: 'slum', flavor: '放浪', color: 'bg-itako-sand', description: '10代で詩を書き捨て、アフリカへ消えた伝説の放浪者。', avatar: null },
  { id: 'fumiko', face: 1, pos: 6, name: '金子文子', role: '浮浪・アナキスト', homeLocationId: 'underpass', flavor: '自己', color: 'bg-red-950/60', isMainChar: true, description: '国家を否定し、ガード下や独房で「自己」の主体性を貫いた。無籍者。', avatar: 'assets/fumiko_warhol.webp', isPreStyled: true },
  { id: 'atsuko', face: 1, pos: 7, name: 'Atsuko', role: '古本屋の店主', homeLocationId: 'archive_room', flavor: '見守り', color: 'bg-itako-sand', isMainChar: true, description: '広場の地下深く、崩れかけの書庫で古本を売る。すべてを記録し、観察する不気味な存在。', avatar: 'assets/atsuko_warhol.webp', isPreStyled: true },
  { id: 'osugi', face: 1, pos: 8, name: '大杉栄', role: '思想家・アナキスト', homeLocationId: 'prison', flavor: '生の拡充', color: 'bg-red-900/70', description: '自由を愛し、生の拡充を説いたアナキスト。甘粕事件の犠牲となった後も、その精神は乱調の中に輝く。', avatar: 'assets/osugi_sakae_warhol_v2.webp', isPreStyled: true },

  // ── Face 2: 女性の先駆者 ─────────────────────────────────────────────
  { id: 'raicho', face: 2, pos: 0, name: '平塚らいてう', role: '思想家', homeLocationId: 'shrine', flavor: '太陽', color: 'bg-orange-900/50', isMainChar: true, description: '青踏社主宰。元始、女性は太陽であったと宣言した、内なる光を放つ霊。', avatar: 'assets/raicho_warhol.webp', isPreStyled: true },
  { id: 'ichikawa', face: 2, pos: 1, name: '市川房枝', role: '政治家', homeLocationId: 'office', flavor: '厳格', color: 'bg-itako-sage', isMainChar: true, description: '婦人運動家、参議院議員。政治の浄化と有権者の啓発を厳格に説き続ける目標。', avatar: 'assets/ichikawa_warhol.webp', isPreStyled: true },
  { id: 'noe', face: 2, pos: 2, name: '伊藤野枝', role: '思想家・アナキスト', homeLocationId: 'well', flavor: '奔放', color: 'bg-red-900/60', isMainChar: true, description: '大杉栄の伴侶。全てを肯定し、全てを破壊する爆弾のような情熱を持つ。「雑草のように」逞しく生きる魂。', avatar: 'assets/ito_noe_warhol.png', isPreStyled: true },
  { id: 'curie', face: 2, pos: 3, name: 'マリー・キュリー', role: '科学者', homeLocationId: 'lighthouse', flavor: '放射線', color: 'bg-itako-sage', description: '放射性元素を発見し、科学の聖域に女性として踏み込んだ。体は蝕まれていた。', avatar: null },
  { id: 'woolf', face: 2, pos: 4, name: 'ヴァージニア・ウルフ', role: '意識の流れ作家', homeLocationId: 'lake', flavor: '波', color: 'bg-blue-950/60', description: '自分だけの部屋を持つことを訴え、川の中に消えた作家。', avatar: null },
  { id: 'beauvoir', face: 2, pos: 5, name: 'ボーヴォワール', role: '哲学者・作家', homeLocationId: 'cafe', flavor: '実存', color: 'bg-itako-clay', description: '第二の性を書いたフェミニズムの知的母。サルトルと対等であることを貫いた。', avatar: null },
  { id: 'nightingale', face: 2, pos: 6, name: 'ナイチンゲール', role: '看護師・統計学者', homeLocationId: 'altar', flavor: '灯り', color: 'bg-itako-sage', description: '戦場を訪れた天使ではなく、統計と感染管理で戦場を変えた科学者の魂。', avatar: null },
  { id: 'yosano', face: 2, pos: 7, name: '与謝野晶子', role: '歌人', homeLocationId: 'graveyard', flavor: '炎', color: 'bg-red-900/50', description: '「君死にたまことなかれ」と叫び、近代に女性の情念の詩を刻んだ。', avatar: null },
  { id: 'higuchi', face: 2, pos: 8, name: '樋口一葉', role: '明治の作家', homeLocationId: 'market', flavor: '五千円', color: 'bg-itako-sand', description: '貧困の中で24年の生涯に傑作を書き残した。今も紙幣に刻まれている。', avatar: null },

  // ── Face 3: 西洋の魂 ──────────────────────────────────────────────
  { id: 'rand', face: 3, pos: 0, name: 'アイン・ランド', role: '富裕層インタビュアー', homeLocationId: 'throne', flavor: '利己', color: 'bg-zinc-700', isMainChar: true, description: '客観主義者。成功した強者のみにマイクを向け、弱さという寄生を断罪する。', avatar: 'assets/rand_warhol.webp', isPreStyled: true },
  { id: 'alyosha', face: 3, pos: 1, name: 'アリョーシャ', role: '修道士', homeLocationId: 'temple', flavor: '信仰', color: 'bg-itako-sage', isMainChar: true, description: '『カラマーゾフの兄弟』の三男。泥の中でも光を失わず、あらゆる罪を許そうとする。', avatar: null },
  { id: 'socrates', face: 3, pos: 2, name: 'ソクラテス', role: '無知の知', homeLocationId: 'oracle', flavor: '問答', color: 'bg-itako-sand', description: '毒杯を飲み干した哲学者。問いかけだけが残り、答えは常に別の問いになる。', avatar: null },
  { id: 'descartes', face: 3, pos: 3, name: 'デカルト', role: '懐疑論者', homeLocationId: 'mirror', flavor: '我思う', color: 'bg-zinc-700', description: 'すべてを疑い続けた末に「思う自己」だけを信じた。今は夢の中を漂う。', avatar: null },
  { id: 'spinoza', face: 3, pos: 4, name: 'スピノザ', role: 'レンズ研磨師・哲学者', homeLocationId: 'window', flavor: '汎神論', color: 'bg-itako-sage', description: '神イコール自然という異端の思想を、レンズを磨きながら書いた。', avatar: null },
  { id: 'hegel', face: 3, pos: 5, name: 'ヘーゲル', role: '弁証法の巨人', homeLocationId: 'tower', flavor: '止揚', color: 'bg-zinc-700', description: '正反合の弁証法で歴史を裁いた。精神の旅の完成を求めた。', avatar: null },
  { id: 'marx', face: 3, pos: 6, name: 'マルクス', role: '革命家', homeLocationId: 'factory', flavor: '資本', color: 'bg-red-900/60', description: '資本主義の亡霊として、今も世界に出没する。万国の労働者よ、団結せよ。', avatar: null },
  { id: 'freud', face: 3, pos: 7, name: 'フロイト', role: '精神分析家', homeLocationId: 'waiting', flavor: '無意識', color: 'bg-zinc-800', description: '夢と性と死を織り交ぜ、人間の無意識の地図を描いた。', avatar: null },
  { id: 'wittgenstein', face: 3, pos: 8, name: 'ウィトゲンシュタイン', role: '論理哲学者', homeLocationId: 'void', flavor: '沈黙', color: 'bg-zinc-700', description: '語りえないことについては沈黙しなければならない。最後は学校の教師になった。', avatar: null },

  // ── Face 4: 芸術家・詩人 ─────────────────────────────────────────
  { id: 'vangogh', face: 4, pos: 0, name: 'ゴッホ', role: '後期印象派画家', homeLocationId: 'graveyard', flavor: '向日葵', color: 'bg-yellow-900/60', description: '渦を巻く星空と向日葵。耳を切り裂いた孤独な魂が、今もキャンバスで燃えている。', avatar: null },
  { id: 'dali', face: 4, pos: 1, name: 'ダリ', role: 'シュルレアリスト', homeLocationId: 'mirror', flavor: '夢', color: 'bg-itako-clay', description: '溶ける時計と燃えるキリンの夢想家。パラノイア的批判的方法の発明者。', avatar: null },
  { id: 'basho', face: 4, pos: 2, name: '松尾芭蕉', role: '俳諧師', homeLocationId: 'mountain', flavor: '閑さ', color: 'bg-itako-sage', description: '古池や蛙飛び込む水の音。この一句で時空を圧縮した永遠の放浪者。', avatar: null },
  { id: 'shakespeare', face: 4, pos: 3, name: 'シェイクスピア', role: '劇作家', homeLocationId: 'theatre', flavor: '悲劇', color: 'bg-itako-sand', description: 'ハムレット、マクベス、リア王。人間のすべてを舞台に乗せた。', avatar: null },
  { id: 'beethoven', face: 4, pos: 4, name: 'ベートーヴェン', role: '作曲家', homeLocationId: 'roof', flavor: '運命', color: 'bg-zinc-800', description: '聴覚を失いながらも第九を書いた。耳はなくとも、音楽は魂で鳴り続けた。', avatar: null },
  { id: 'chopin', face: 4, pos: 5, name: 'ショパン', role: '詩人のピアノ', homeLocationId: 'piano', flavor: '夜想曲', color: 'bg-itako-sand', description: '亡命ポーランド人として、ピアノで祖国を語り続けた。心臓だけが故郷に帰った。', avatar: null },
  { id: 'hokusai', face: 4, pos: 6, name: '葛飾北斎', role: '浮世絵師', homeLocationId: 'sea', flavor: '波', color: 'bg-blue-950/60', description: '90歳まで筆を持ち、自らを画狂老人と名乗った。富嶽三十六景の波は永遠に砕け続ける。', avatar: null },
  { id: 'rilke', face: 4, pos: 7, name: 'リルケ', role: '詩人', homeLocationId: 'tower', flavor: '天使', color: 'bg-itako-sand', description: 'ドゥイノの悲歌を10年かけて書いた。天使は美しいからこそ恐ろしい。', avatar: null },
  { id: 'dickinson', face: 4, pos: 8, name: 'ディキンソン', role: '隠遁詩人', homeLocationId: 'window', flavor: '不死', color: 'bg-itako-sage', description: '生涯で1789篇の詩を書き、白い服を着て自室に引きこもった。', avatar: null },

  // ── Face 5: 異界の存在 ──────────────────────────────────────────────
  { id: 'future_self', face: 5, pos: 0, name: '未来の自分', role: '時空の旅人', homeLocationId: 'gate', flavor: '予言', color: 'bg-zinc-700', isMainChar: true, description: '2036年の「あなた自身」。10年前の自分を静かに見守り、ときに語りかける。', avatar: null },
  { id: 'oracle_ghost', face: 5, pos: 1, name: '巫女の霊', role: '神託者', homeLocationId: 'oracle', flavor: '予兆', color: 'bg-purple-950/60', description: '過去と未来を同時に見透かす存在。言葉は常に二重の意味を持つ。', avatar: null },
  { id: 'void_entity', face: 5, pos: 2, name: '虚無の声', role: '無名の存在', homeLocationId: 'void', flavor: '無言', color: 'bg-zinc-900', description: '名前も形もない。ただ「問い」だけが残された。', avatar: null },
  { id: 'shadow', face: 5, pos: 3, name: '影', role: 'あなたの影', homeLocationId: 'mirror_abyss', flavor: '境界', color: 'bg-zinc-800', description: 'ユングの言う「シャドウ」。抑圧されたすべてが集まった、もう一人の自分。', avatar: null },
  { id: 'anima', face: 5, pos: 4, name: 'アニマ', role: '魂の女性像', homeLocationId: 'lake', flavor: '深層', color: 'bg-blue-950/50', description: '男性の無意識に宿る女性原理。夢の中の謎めいた声の正体。', avatar: null },
  { id: 'trickster', face: 5, pos: 5, name: 'トリックスター', role: '道化・境界の怪物', homeLocationId: 'neon', flavor: '混沌', color: 'bg-yellow-900/50', description: '神話的なトリックスター。秩序を破壊し、新しい秩序を生む境界の存在。', avatar: null },
  { id: 'persona', face: 5, pos: 6, name: 'ペルソナ', role: '仮面', homeLocationId: 'theatre', flavor: '演技', color: 'bg-zinc-700', description: '社会に見せる顔。本当の自己とは何かを問い続けるもう一つの「私」。', avatar: null },
  { id: 'itako_spirit', face: 5, pos: 7, name: 'イタコの霊', role: '口寄せ', homeLocationId: 'core', flavor: '媒介', color: 'bg-purple-950/50', description: 'この広場の源。死者の言葉を生者に伝える、口寄せの霊的媒介者。', avatar: null },
  { id: 'end_being', face: 5, pos: 8, name: '終焉の者', role: '完了', homeLocationId: 'end', flavor: '完結', color: 'bg-zinc-900', description: 'すべての物語の最後に現れる存在。始まりとは終わりのことである。', avatar: null },
  { id: 'mob_s', face: 5, pos: 9, name: '匿名S', role: '群衆', homeLocationId: 'neon', flavor: '流言', color: 'bg-zinc-800', description: '特定の顔を持たない「普通の人」。流言飛語に弱く、集団心理に容易に呑み込まれ、自覚なき加害者となる狂気を秘めている。', avatar: null },
  { id: 'mob_u', face: 5, pos: 10, name: '匿名U', role: '群衆', homeLocationId: 'market', flavor: '同調', color: 'bg-zinc-800', description: '善良に見える匿名の市民。パニック時には周囲に同調してしまい、無防備な魂を追い詰める側に回る。', avatar: null },
  { id: 'narrator', face: 5, pos: 11, name: '語り手', role: '観測', homeLocationId: 'void', flavor: '情景', color: 'bg-transparent', description: 'この世界で起こる事象、暴動、虐殺の空気を客観的かつ不気味に語る聲。', avatar: null },
];

export const INITIAL_LOCATIONS = [
  { id: 'cafe', name: 'カフェ', face: 0, pos: 0, tags: ['narrow'], description: '微かなコーヒーの香りが生者の執着を思い出させる。', color: '#1a1a1a', pattern: 'radial-gradient(circle, #222 1px, transparent 1px)' },
  { id: 'library', name: '図書館', face: 0, pos: 1, tags: ['quiet'], description: '開かれることのない蔵書たちが、重力のような沈黙を強いている。', color: '#0f141a', pattern: 'linear-gradient(45deg, #ffffff03 25%, transparent 25%)' },
  { id: 'garden', name: '庭園', face: 0, pos: 2, tags: ['wide', 'nature'], description: '枯れない花々。時間はここでは結晶化している。', color: '#0f1a0f', pattern: 'radial-gradient(circle, #1a2a1a 1px, transparent 1px)' },
  { id: 'elevator', name: '昇降機', face: 0, pos: 3, tags: ['narrow'], description: '閉ざされた立方体。目的地のない沈黙。', color: '#111', pattern: 'linear-gradient(to bottom, #222 1px, transparent 1px)' },
  { id: 'park', name: '広い公園', face: 0, pos: 4, tags: ['wide'], description: '空が剥き出しの場所。誰ともすれ違わない散歩道。', color: '#1a2a1a', pattern: 'radial-gradient(circle at 50% 50%, #2a3a2a 20%, transparent 80%)' },
  { id: 'market', name: '市場', face: 0, pos: 5, tags: ['noisy'], description: '物々交換される記憶。中身のない言葉が飛び交う。', color: '#1a150f', pattern: 'repeating-linear-gradient(45deg, #222, #222 2px, transparent 2px, transparent 10px)' },
  { id: 'school', name: '校舎', face: 0, pos: 6, tags: ['quiet'], description: '永遠に終わらない放課後のチャイム。', color: '#151a20', pattern: 'linear-gradient(to bottom, #1a2a3a 1px, transparent 1px)' },
  { id: 'roof', name: '屋上', face: 0, pos: 7, tags: ['wide'], description: 'フェンスの向こう側は、何もない空。', color: '#0a1015', pattern: 'linear-gradient(to bottom, #1a2a3a, transparent)' },
  { id: 'theatre', name: '劇場', face: 0, pos: 8, tags: ['wide'], description: '観客のいない舞台。拍手の残響だけが揺れている。', color: '#1a0505', pattern: 'radial-gradient(ellipse at center, #300 0%, transparent 70%)' },
  { id: 'passage', name: '地下通路', face: 1, pos: 0, tags: ['narrow'], description: 'すべての後悔へと通じている冷たいコンクリートの回廊。', color: '#050505', pattern: 'repeating-linear-gradient(0deg, #111 0, #111 1px, transparent 0, transparent 20px)' },
  { id: 'stair', name: '螺旋階段', face: 1, pos: 1, tags: ['narrow'], description: '上っても下っても、同じ階層に辿り着く。', color: '#0a0a0a', pattern: 'conic-gradient(from 0deg, #111, #000)' },
  { id: 'mirror', name: '鏡の間', face: 1, pos: 2, tags: ['narrow'], description: '自分以外のすべてが映る鏡。', color: '#101015', pattern: 'linear-gradient(135deg, #222 25%, transparent 25%)' },
  { id: 'waiting', name: '待合室', face: 1, pos: 3, tags: ['quiet'], description: 'いつまでも来ない列車を待つ影たち。', color: '#0f0f0f', pattern: 'radial-gradient(circle, #222 2px, transparent 2px)' },
  { id: 'prison', name: '独房', face: 1, pos: 4, tags: ['narrow'], description: '自己との対面を強いる最小限の空間。', color: '#111', pattern: 'none' },
  { id: 'window', name: '額縁の窓', face: 1, pos: 5, tags: ['quiet'], description: '風景を切り取ったまま動かない。', color: '#050a15', pattern: 'linear-gradient(to bottom, #0a1a2a, transparent)' },
  { id: 'door', name: '開かずの扉', face: 1, pos: 6, tags: ['narrow'], description: '鍵のない境界線。向こう側の気配。', color: '#150505', pattern: 'linear-gradient(to right, #200, transparent)' },
  { id: 'box', name: '暗室', face: 1, pos: 7, tags: ['narrow'], description: '意識だけが漂う暗闇。', color: '#000', pattern: 'none' },
  { id: 'archive_room', name: '地下書庫', face: 1, pos: 8, tags: ['quiet'], description: '湿った紙の断片が、誰かの一生を黙殺している。', color: '#0a0505', pattern: 'repeating-linear-gradient(0deg, #211, #000 2px)' },
  { id: 'shrine', name: '神社', face: 2, pos: 0, tags: ['quiet'], description: '形なき祈りだけが風に震えている。', color: '#1a0f0f', pattern: 'radial-gradient(circle, #300 2px, transparent 2px)' },
  { id: 'altar', name: '祭壇', face: 2, pos: 1, tags: ['quiet'], description: '供えられたのは、名もなき者の悔恨。', color: '#150f15', pattern: 'radial-gradient(circle at 50% 50%, #202, transparent)' },
  { id: 'temple', name: '寺院', face: 2, pos: 2, tags: ['wide'], description: '鐘の音は空へは昇らず、地へと染み込む。', color: '#0f0f05', pattern: 'repeating-conic-gradient(#110 0deg 10deg, #000 10deg 20deg)' },
  { id: 'forest', name: '鎮守の森', face: 2, pos: 3, tags: ['nature', 'wide'], description: '木々の隙間に、誰かの瞳が光る。', color: '#051005', pattern: 'radial-gradient(circle, #020 3px, transparent 3px)' },
  { id: 'lake', name: '静かな湖', face: 2, pos: 4, tags: ['wide', 'nature'], description: '波紋のない水面。深淵の入口。', color: '#0a1a1a', pattern: 'radial-gradient(ellipse at center, #0a2a2a 0%, #000 70%)' },
  { id: 'mountain', name: '虚無山', face: 2, pos: 5, tags: ['wide', 'nature'], description: '道のない山。登るほどに自分を失う。', color: '#1a1005', pattern: 'linear-gradient(to top, #210, transparent)' },
  { id: 'graveyard', name: '墓地', face: 2, pos: 6, tags: ['quiet'], description: '名前が削れた石碑。死者さえ忘れた墓。', color: '#0a0f0a', pattern: 'radial-gradient(circle, #121 1px, transparent 1px)' },
  { id: 'tower', name: '五重塔', face: 2, pos: 7, tags: ['narrow'], description: '天への梯子。途中で途切れている。', color: '#1a1005', pattern: 'linear-gradient(to top, #210, transparent)' },
  { id: 'cliff', name: '断崖', face: 2, pos: 8, tags: ['nature'], description: 'ここから先は、言葉のない領域。', color: '#0a0a0a', pattern: 'linear-gradient(to top, #111, transparent)' },
  { id: 'backalley', name: '路地裏', face: 3, pos: 0, tags: ['narrow'], description: '捨てられた概念が腐敗している。', color: '#0a0a0a', pattern: 'radial-gradient(circle, #1a1a1a 1px, transparent 1px)' },
  { id: 'casino', name: '賽の河原賭博場', face: 3, pos: 1, tags: ['gambling', 'narrow'], description: '魂を賭けてサイコロを振る、終わりのない遊戯。', color: '#1a0505', pattern: 'radial-gradient(circle at center, #300 0%, #000 80%)' },
  { id: 'neon', name: 'ネオン街', face: 3, pos: 2, tags: ['noisy'], description: '電圧の低い欲望。明滅する幽霊文字。', color: '#0a051a', pattern: 'linear-gradient(90deg, #102 1px, transparent 1px)' },
  { id: 'junkyard', name: '廃材置場', face: 3, pos: 3, tags: ['wide'], description: '意味を失った機械たちの、冷たい囁き。', color: '#1a1a1a', pattern: 'repeating-linear-gradient(45deg, #222, #000 5px)' },
  { id: 'underpass', name: 'ガード下', face: 3, pos: 4, tags: ['narrow'], description: '絶え間ない振動。誰の足音でもない。', color: '#050505', pattern: 'linear-gradient(transparent 50%, #111 50%)' },
  { id: 'slum', name: '裏通りの吹き溜まり', face: 3, pos: 5, tags: ['narrow'], description: '希望が廃棄された場所。', color: '#1a0a05', pattern: 'none' },
  { id: 'canal', name: '運河', face: 3, pos: 6, tags: ['wide'], description: 'オイルの浮いた水面が、偽物の月を映す。', color: '#051010', pattern: 'radial-gradient(circle at 10% 10%, #122, transparent)' },
  { id: 'port', name: '亡霊の港', face: 3, pos: 7, tags: ['wide'], description: '出航しない船だけが繋がれている。', color: '#0a1015', pattern: 'none' },
  { id: 'factory', name: '廃工場', face: 3, pos: 8, tags: ['wide'], description: 'リズムだけが生き続ける、主のいない生産ライン。', color: '#111', pattern: 'repeating-linear-gradient(90deg, #222 0, #222 2px, transparent 0, transparent 40px)' },
  { id: 'bridge', name: '橋', face: 4, pos: 0, tags: ['wide'], description: '過去の記憶をどこか遠くへ運んでいく。', color: '#0f1a1a', pattern: 'linear-gradient(to right, #ffffff05 1px, transparent 1px)' },
  { id: 'station', name: '無人駅', face: 4, pos: 1, tags: ['wide'], description: '改札口を通る者は、もう誰もいない。', color: '#151515', pattern: 'repeating-linear-gradient(90deg, #222, #222 1px, transparent 1px, transparent 50px)' },
  { id: 'pier', name: '桟橋', face: 4, pos: 2, tags: ['narrow'], description: '霧の向こうから、呼び聲が聞こえる。', color: '#101520', pattern: 'radial-gradient(circle, #1a2030 1px, transparent 1px)' },
  { id: 'sea', name: '亡霊の海', face: 4, pos: 3, tags: ['wide', 'nature'], description: '岸のない海。記憶が塩分となって溶けている。', color: '#050a15', pattern: 'radial-gradient(ellipse at 50% 100%, #0a2a4a 0%, #000 80%)' },
  { id: 'lighthouse', name: '灯台', face: 4, pos: 4, tags: ['narrow'], description: '光は魂を導かず、ただ闇を薙ぎ払う。', color: '#1a1a05', pattern: 'conic-gradient(from 180deg at 50% 0%, #331, transparent)' },
  { id: 'beach', name: '砂浜', face: 4, pos: 5, tags: ['wide', 'nature'], description: '打ち寄せられるのは、漂流した未練。', color: '#1a1a15', pattern: 'radial-gradient(ellipse, #222, transparent)' },
  { id: 'island', name: '浮島', face: 4, pos: 6, tags: ['nature'], description: '根を持たない地。浮遊する虚無。', color: '#101010', pattern: 'radial-gradient(circle, #222, transparent 50%)' },
  { id: 'ship', name: '難破船', face: 4, pos: 7, tags: ['narrow'], description: '沈みきれないまま漂う後悔の船体。', color: '#0a0a0a', pattern: 'none' },
  { id: 'bottom', name: '海底', face: 4, pos: 8, tags: ['wide', 'quiet'], description: 'すべての音が光と共に消え去る場所。', color: '#000510', pattern: 'none' },
  { id: 'core', name: '核', face: 5, pos: 0, tags: ['narrow'], description: 'すべての魂が収束し、消失する点。', color: '#000000', pattern: 'radial-gradient(circle, #111 2px, transparent 2px)' },
  { id: 'monolith', name: '方尖柱', face: 5, pos: 1, tags: ['narrow'], description: '天を貫く垂直の意志。文字が刻まれている。', color: '#050505', pattern: 'linear-gradient(to right, #1a1a1a, transparent)' },
  { id: 'oracle', name: '神託所', face: 5, pos: 2, tags: ['quiet'], description: '返ってくるのは自分の声だけ。', color: '#050a0a', pattern: 'radial-gradient(circle, #122 1px, transparent 1px)' },
  { id: 'void', name: '虚無', face: 5, pos: 3, tags: ['wide'], description: '色も音も、名前も。すべてが許されない場所。', color: '#000000', pattern: 'none' },
  { id: 'archive', name: '終焉書庫', face: 5, pos: 4, tags: ['quiet'], description: '宇宙の終わりの一秒前まで記された記録。', color: '#0a0505', pattern: 'repeating-linear-gradient(0deg, #211, #000 2px)' },
  { id: 'gate', name: '門', face: 5, pos: 5, tags: ['narrow'], description: '本当の出口か、あるいは永遠の入り口か。', color: '#000000', pattern: 'linear-gradient(45deg, #111 25%, transparent 25%)' },
  { id: 'throne', name: '空の玉座', face: 5, pos: 6, tags: ['wide'], description: '支配なき支配者が坐る、絶対的な不在。', color: '#050505', pattern: 'none' },
  { id: 'mirror_abyss', name: '深淵の鏡', face: 5, pos: 7, tags: ['narrow'], description: '覗き込む時、向こう側もあなたを見ている。', color: '#000', pattern: 'radial-gradient(circle at center, #111, transparent)' },
  { id: 'end', name: '終焉', face: 5, pos: 8, tags: ['wide'], description: 'すべてが完了し、新たな静止が始まる。', color: '#111', pattern: 'none' },
  { id: 'piano', name: '廃ピアノの間', face: 4, pos: 9, tags: ['quiet'], description: '鍵盤に指が触れると、存在しないはずの音が鳴る。', color: '#0a0505', pattern: 'repeating-linear-gradient(90deg, #111, #000 2px)' },
  { id: 'office', name: '執務室', face: 0, pos: 9, tags: ['quiet'], description: '永遠に片付かない書類の山。誰かの志が積み重なっている。', color: '#111520', pattern: 'none' },
];

export const AMBIENT_COLORS = {
  neutral: { color: '#000000', pattern: 'radial-gradient(circle, #111 2px, transparent 2px)' },
  serene: { color: '#051515', pattern: 'radial-gradient(circle at 50% 50%, #0a2a2a 0%, #000 80%)' },
  agitated: { color: '#1a0505', pattern: 'radial-gradient(ellipse at center, #300 0%, transparent 70%)' },
  melancholic: { color: '#0a0a15', pattern: 'linear-gradient(to bottom, #1a2a3a 1px, transparent 1px)' },
  joyful: { color: '#1a1505', pattern: 'radial-gradient(circle, #2a2005 2px, transparent 2px)' },
  chaotic: { color: '#0f0515', pattern: 'repeating-linear-gradient(45deg, #102 0, #102 1px, transparent 0, transparent 20px)' },
};
