// 繧ｭ繝｣繝ｩ繧ｯ繧ｿ繝ｼ螳夂ｾｩ
// face: 0=譁・ｱｪ蛻嶺ｼ・Front), 1=髣・・邉ｻ隴・Back), 2=螂ｳ諤ｧ縺ｮ蜈磯ｧ・・Right),
//        3=隘ｿ豢九・鬲・Left), 4=闃ｸ陦灘ｮｶ繝ｻ隧ｩ莠ｺ(Top), 5=豁ｴ蜿ｲ縺ｨ螳玲蕗(Bottom)

export const INITIAL_CHARACTERS = [
  // 笏笏 Face 0: 譁・ｱｪ蛻嶺ｼ・笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏
  { id: 'soseki', face: 0, pos: 0, name: '螟冗岼貍ｱ遏ｳ', role: '螟ｧ蟄ｦ謨呎肢', homeLocationId: 'school', flavor: '閭・李', color: 'bg-itako-clay', isMainChar: true, description: '霑台ｻ｣譌･譛ｬ莠ｺ縺ｮ蟄､迢ｬ縺ｨ蛟ｫ逅・ｒ蜈区・縺ｫ謠上＞縺滓枚雎ｪ縲ゅ瑚・蟾ｱ譛ｬ菴阪阪°繧峨悟援螟ｩ蜴ｻ遘√阪∈縲・, avatar: 'assets/soseki_warhol.webp', isPreStyled: true },
  { id: 'ogai', face: 0, pos: 1, name: '譽ｮ魘主､・, role: '霆榊現繝ｻ譁・ｱｪ', homeLocationId: 'library', flavor: '遏･諤ｧ', color: 'bg-zinc-700', description: '蜀ｷ蠕ｹ縺ｪ逅・ｧ縺ｮ蜈峨ｒ謾ｾ縺｡邯壹￠縺溽衍諤ｧ縺ｮ蟾ｨ莠ｺ縲ょ彰莨晄枚蟄ｦ縺ｧ豁ｻ逕溯ｦｳ繧呈･ｵ繧√◆縲・, avatar: 'assets/ogai_warhol_v3.png', isPreStyled: true },
  { id: 'akutagawa', face: 0, pos: 2, name: '闃･蟾晞ｾ堺ｹ倶ｻ・, role: '鬯ｼ謇堺ｽ懷ｮｶ', homeLocationId: 'mirror', flavor: '荳榊ｮ・, color: 'bg-red-950/50', description: '遏ｭ邱ｨ蟆剰ｪｬ縺ｮ鬯ｼ謇阪よ･ｵ髯舌・謚蟾ｧ縺ｧ莠ｺ髢薙・讌ｭ繧呈垓縺阪√瑚埋縺ｼ繧薙ｄ繧翫＠縺滉ｸ榊ｮ峨阪・荳ｭ縺ｧ閾ｪ豎ｺ縺励◆縲・, avatar: 'assets/akutagawa_warhol_v3.png', isPreStyled: true },
  { id: 'dazai', face: 0, pos: 3, name: '螟ｪ螳ｰ豐ｻ', role: '諱･縺ｮ螟壹＞逕滓ｶｯ', homeLocationId: 'canal', flavor: '螟ｱ譬ｼ', color: 'bg-zinc-800', description: '閾ｪ諢剰ｭ倥・蝨ｰ迯・ｒ譖ｸ縺咲ｶ壹￠縺溽┌鬆ｼ豢ｾ縲る％蛹悶→縺励※縺ｮ隱螳溘＆繧呈・縺ｨ邨ｶ譛帙・荳ｭ縺ｫ豎ゅａ縺溘・, avatar: 'assets/dazai_warhol.png', isPreStyled: true },
  { id: 'mishima', face: 0, pos: 4, name: '荳牙ｳｶ逕ｱ邏螟ｫ', role: '菴懷ｮｶ繝ｻ豁ｦ莠ｺ', homeLocationId: 'roof', flavor: '鄒弱→豁ｻ', color: 'bg-red-900/60', description: '邱ｻ蟇・↑隲也炊縺ｨ閧我ｽ薙・骰幃軒縺ｧ遨ｶ讌ｵ縺ｮ鄒弱ｒ讒狗ｯ峨ょ牡閻ｹ閾ｪ谿ｺ縺ｫ繧医ｊ閾ｪ繧峨・迚ｩ隱槭ｒ螳檎ｵ舌＆縺帙◆縲・, avatar: 'assets/mishima_warhol.png', isPreStyled: true },
  { id: 'kawabata', face: 0, pos: 5, name: '蟾晉ｫｯ蠎ｷ謌・, role: '繝弱・繝吶Ν雉樔ｽ懷ｮｶ', homeLocationId: 'garden', flavor: '菴咎渊', color: 'bg-itako-sage', description: '髱呵ｬ舌↑鄒取э隴倥〒縲∵律譛ｬ縺ｮ蟷ｽ邇・→豁ｻ逕溯ｦｳ繧剃ｸ也阜縺ｸ遏･繧峨＠繧√◆縲・, avatar: 'assets/kawabata_warhol.png', isPreStyled: true },
  { id: 'kafuka', face: 0, pos: 6, name: '繧ｫ繝輔き', role: '菫晞匱螻蜩｡繝ｻ菴懷ｮｶ', homeLocationId: 'waiting', flavor: '螟芽ｺｫ', color: 'bg-zinc-700', description: '譌･蟶ｸ縺ｮ陬ゅ￠逶ｮ縺ｫ遯∝ｦら樟繧後ｋ縲御ｸ肴擅逅・阪ｒ謠上＞縺溘りｿｷ螳ｮ縺ｮ繧医≧縺ｪ螳伜・讖滓ｧ九→辷ｶ縺ｨ縺ｮ遒ｺ蝓ｷ縲・, avatar: 'assets/kafka_warhol.png', isPreStyled: true },
  { id: 'borges', face: 0, pos: 7, name: '繝懊Ν繝倥せ', role: '蝗ｳ譖ｸ鬢ｨ蜿ｸ譖ｸ', homeLocationId: 'archive', flavor: '霑ｷ螳ｮ', color: 'bg-itako-sand', description: '蜊夊ｦｧ蠑ｷ險倥・霑ｷ螳ｮ縲ょ・迺ｰ縺吶ｋ譎る俣縲・升縺ｮ螳・ｮ吶ｒ蟷ｻ隕悶＠縺溘い繝ｫ繧ｼ繝ｳ繝√Φ縺ｮ閾ｳ螳昴・, avatar: 'assets/borges_warhol.png', isPreStyled: true },
  { id: 'k_kokoro', face: 0, pos: 8, name: 'K', role: '辟｡閨ｷ繝ｻ譖ｸ逕・, homeLocationId: 'stair', flavor: '隕壽ぁ', color: 'bg-zinc-800', isMainChar: true, description: '螟冗岼貍ｱ遏ｳ縲弱％縺薙ｍ縲上↓蝗壹ｏ繧後◆險伜捷逧・ｮ溷ｭ倥る％縺ｨ霑ｷ螳ｮ縺ｮ髢薙〒陞ｺ譌九ｒ蠖ｷ蠕ｨ縺・・, avatar: 'assets/k_kokoro_warhol.png', isPreStyled: true },
  { id: 'hyakken', face: 0, pos: 9, name: '蜀・伐逋ｾ髢・, role: '髫冗ｭ・ｮｶ', homeLocationId: 'station', flavor: '蜀･騾・, color: 'bg-zinc-800', description: '蛛丞ｱ医・鄒主ｭｦ縲よ律蟶ｸ縺ｮ陬ゅ￠逶ｮ縺ｫ貎懊・縲悟・騾斐阪・豌鈴・繧定ｫｧ隰皮噪縺ｫ謠上″蜃ｺ縺励◆縲・, avatar: 'assets/hyakken_warhol.png', isPreStyled: true },

  // 笏笏 Face 1: 髣・・邉ｻ隴・笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏
  { id: 'dosto', face: 1, pos: 0, name: '繝峨せ繝医お繝輔せ繧ｭ繝ｼ', role: '蛯ｵ蜍呵・・菴懷ｮｶ', homeLocationId: 'casino', flavor: '豺ｱ豺ｵ', color: 'bg-itako-sand', isMainChar: true, description: '莠ｺ髢薙・髱槫粋逅・↑蜍墓ｩ溘ｒ逶ｴ隕悶＠縲∝粋逅・ｸｻ鄒ｩ繧貞凄螳壹ゅ・繝ｪ繝輔か繝九・縺ｧ鬲ゅｒ隗｣蜑悶＠縺溘・, avatar: 'assets/dosto_warhol.webp', isPreStyled: true },
  { id: 'nietzsche', face: 1, pos: 1, name: '繝九・繝√ぉ', role: '蜿榊憧蟄ｦ閠・, homeLocationId: 'monolith', flavor: '雜・ｺｺ', color: 'bg-zinc-700', description: '逾槭・豁ｻ蠕後・荳也阜縺ｧ萓｡蛟､繧呈遠縺｡遐輔″縲√碁°蜻ｽ諢帙阪ｒ隱ｬ縺・◆縲・, avatar: 'assets/nietzsche_warhol.png', isPreStyled: true },
  { id: 'poe', face: 1, pos: 2, name: '繧ｨ繝峨ぎ繝ｼ繝ｻ繧｢繝ｩ繝ｳ繝ｻ繝昴・', role: '蟷ｻ諠ｳ菴懷ｮｶ', homeLocationId: 'box', flavor: '螂郁誠', color: 'bg-zinc-800', description: '謗ｨ逅・ｰ剰ｪｬ縺ｮ逾悶よ焚蟄ｦ逧・ｫ也炊縺ｨ繧ｴ繧ｷ繝・け縺ｮ諱先悶ｒ陞榊粋縺輔○縺溘・, avatar: 'assets/poe_warhol.png', isPreStyled: true },
  { id: 'kropotkin', face: 1, pos: 3, name: '繧ｯ繝ｭ繝昴ヨ繧ｭ繝ｳ', role: '遘大ｭｦ閠・・繧｢繝翫く繧ｹ繝・, homeLocationId: 'forest', flavor: '逶ｸ莠呈恩蜉ｩ', color: 'bg-red-950/70', description: '騾ｲ蛹悶・骰ｵ縺ｯ蜊泌鴨縺ｫ縺ゅｋ縺ｨ隱ｬ縺上檎嶌莠呈恩蜉ｩ縲崎ｫ悶ｒ謠仙罰縺励◆遘大ｭｦ閠・↓縺励※髱ｩ蜻ｽ螳ｶ縲・, avatar: 'assets/kropotkin_warhol.png', isPreStyled: true },
  { id: 'kobayashi', face: 1, pos: 4, name: '蟆乗棊遘髮・, role: '譁・敢隧戊ｫ門ｮｶ', homeLocationId: 'archive_room', flavor: '辟｡蟶ｸ', color: 'bg-zinc-700', description: '蛻・梵縺ｧ縺ｯ縺ｪ縺冗峩隕ｳ逧・↑縲悟多縲阪・諢溷女繧帝㍾繧薙§縺滓律譛ｬ縺ｮ霑台ｻ｣謇ｹ隧輔・逾悶・, avatar: 'assets/kobayashi_warhol_v3.png', isPreStyled: true },
  { id: 'rimbaud', face: 1, pos: 5, name: '繝ｩ繝ｳ繝懊・', role: '螟ｩ謇榊ｰ大ｹｴ隧ｩ莠ｺ', homeLocationId: 'slum', flavor: '謾ｾ豬ｪ', color: 'bg-itako-sand', description: '諢溯ｦ壹ｒ骭ｯ荵ｱ縺輔○繧九瑚ｦ玖・阪・驕薙よ掠辭溘↑螟ｩ謇阪′20豁ｳ縺ｧ譁・ｭｦ繧呈昏縺ｦ縺溘・, avatar: 'assets/rimbaud_warhol.png', isPreStyled: true },
  { id: 'fumiko', face: 1, pos: 6, name: '驥大ｭ先枚蟄・, role: '繧｢繝翫く繧ｹ繝・, homeLocationId: 'underpass', flavor: '閾ｪ蟾ｱ', color: 'bg-red-950/60', isMainChar: true, description: '邨ｶ蟇ｾ蟷ｳ遲峨→蜿榊嵜螳ｶ繧定ｪｬ縺阪∝・讓ｩ螽√ｒ蜷ｦ螳壹＠縺溯劒辟｡逧・倶ｺｺ荳ｻ鄒ｩ縺ｮ菴鍋樟閠・・, avatar: 'assets/fumiko_warhol.webp', isPreStyled: true },
  { id: 'atsuko', face: 1, pos: 7, name: 'Atsuko', role: '隕ｳ貂ｬ閠・, homeLocationId: 'archive_room', flavor: '險倬鹸', color: 'bg-itako-sand', isMainChar: true, description: '蝨ｰ荳区嶌蠎ｫ縺ｮ荳ｻ縲ょｺ・ｴ縺ｮ豁ｴ蜿ｲ逧・↑逶幄｡ｰ・医い繧ｵ繝薙・繝､縺ｮ貂幄｡ｰ・峨ｒ髱吶°縺ｫ險倬鹸縺礼ｶ壹￠繧九・, avatar: 'assets/atsuko_warhol.webp', isPreStyled: true },
  { id: 'osugi', face: 1, pos: 8, name: '螟ｧ譚画・, role: '諤晄Φ螳ｶ繝ｻ繧｢繝翫く繧ｹ繝・, homeLocationId: 'prison', flavor: '逕溘・諡｡蜈・, color: 'bg-red-900/70', description: '縲檎函縺ｮ諡｡蜈・阪ｒ謗ｲ縺偵√≠繧峨ｆ繧区ｨｩ蜉帙ｒ蜷ｦ螳壹＠縺滓律譛ｬ繧｢繝翫・繧ｭ繧ｺ繝縺ｮ雎｡蠕ｴ縲・, avatar: 'assets/osugi_sakae_warhol_v2.webp', isPreStyled: true },
  { id: 'bakunin', face: 1, pos: 9, name: '繝舌け繝ｼ繝九Φ', role: '荳榊ｱ医・髱ｩ蜻ｽ螳ｶ', homeLocationId: 'prison', flavor: '遐ｴ螢・, color: 'bg-red-950/70', description: '蝗ｽ螳ｶ縺ｮ螳悟・蟒・ｭ｢繧剃ｸｻ蠑ｵ縲ゅ檎ｴ螢翫・諠・・縺ｯ縲∝酔譎ゅ↓蜑ｵ騾縺ｮ諠・・縺ｧ繧ゅ≠繧九阪→隱ｬ縺・◆縲・, avatar: 'assets/bakunin_warhol.png', isPreStyled: true },

  // 笏笏 Face 2: 螂ｳ諤ｧ縺ｮ蜈磯ｧ・・笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏
  { id: 'raicho', face: 2, pos: 0, name: '蟷ｳ蝪壹ｉ縺・※縺・, role: '諤晄Φ螳ｶ', homeLocationId: 'shrine', flavor: '螟ｪ髯ｽ', color: 'bg-orange-900/50', isMainChar: true, description: '逵溘・閾ｪ蟾ｱ・亥､ｪ髯ｽ・峨・螂ｪ驍・ｒ謗ｲ縺偵∫┌髯舌・逕滓・繧偵ｂ縺｣縺ｦ蠢・・髱ｩ蜻ｽ繧剃ｿ・＠縺溷・鬧・・・, avatar: 'assets/raicho_warhol.webp', isPreStyled: true },
  { id: 'ichikawa', face: 2, pos: 1, name: '蟶ょｷ晄袷譫・, role: '謾ｿ豐ｻ螳ｶ', homeLocationId: 'office', flavor: '貂・ｻ・, color: 'bg-itako-sage', isMainChar: true, description: '螂ｳ諤ｧ蜿よ帆讓ｩ迯ｲ蠕励↓謖ｺ霄ｫ縲ゅ梧帆豐ｻ縺ｨ蜿ｰ謇繧堤ｵ舌・縲咲函豢ｻ閠・ｦ也せ繧定ｲｫ縺・◆縲・, avatar: 'assets/ichikawa_warhol.webp', isPreStyled: true },
  { id: 'noe', face: 2, pos: 2, name: '莨願陸驥取椌', role: '諠・・螳ｶ', homeLocationId: 'well', flavor: '蜷ｹ荳鬚ｨ', color: 'bg-red-900/60', isMainChar: true, description: '閾ｪ繧峨・逕溘・謾ｾ辭ｱ縺ｫ隱螳溘↓逕溘″繧九％縺ｨ繧定ｲｫ縺・◆縲√ｏ縺阪∪縺医↑縺・九・雎｡蠕ｴ縲・, avatar: 'assets/ito_noe_warhol.png', isPreStyled: true },
  { id: 'curie', face: 2, pos: 3, name: '繝槭Μ繝ｼ繝ｻ繧ｭ繝･繝ｪ繝ｼ', role: '遘大ｭｦ閠・, homeLocationId: 'lighthouse', flavor: '迪ｮ霄ｫ', color: 'bg-itako-sage', description: '遏･諤ｧ縺ｨ蜍・ｰ励ｒ繧ゅ▲縺ｦ譛ｪ遏･縺ｮ逵溽炊繧堤・繧峨＠縺溽ｧ大ｭｦ縺ｸ縺ｮ迪ｮ霄ｫ閠・・, avatar: 'assets/curie_warhol.png', isPreStyled: true },
  { id: 'woolf', face: 2, pos: 4, name: '繝ｴ繧｡繝ｼ繧ｸ繝九い繝ｻ繧ｦ繝ｫ繝・, role: '菴懷ｮｶ', homeLocationId: 'lake', flavor: '諢剰ｭ・, color: 'bg-blue-950/60', description: '諢剰ｭ倥・豬√ｌ縺ｫ繧医ｊ豬∝虚逧・↑蜀・擇荳也阜繧呈緒縺・◆繝｢繝繝九ぜ繝縺ｮ譌玲焔縲・, avatar: 'assets/woolf_warhol.png', isPreStyled: true },
  { id: 'beauvoir', face: 2, pos: 5, name: '繝懊・繝ｴ繧ｩ繝ｯ繝ｼ繝ｫ', role: '蜩ｲ蟄ｦ閠・, homeLocationId: 'cafe', flavor: '螳溷ｭ・, color: 'bg-itako-clay', description: '縲悟･ｳ縺ｫ縺ｪ繧九榊ｮ溷ｭ倥・閾ｪ逕ｱ縺ｨ縲∫､ｾ莨夂噪縺ｪ讒狗ｯ峨∈縺ｮ蛻・梵繧定ｪｬ縺・◆遏･諤ｧ縺ｮ雎｡蠕ｴ縲・, avatar: 'assets/beauvoir_warhol.png', isPreStyled: true },
  { id: 'nightingale', face: 2, pos: 6, name: '繝翫う繝√Φ繧ｲ繝ｼ繝ｫ', role: '邂｡逅・・, homeLocationId: 'altar', flavor: '逅・ｧ逧・・謔ｲ', color: 'bg-itako-sage', description: '邨ｱ險医→逅・ｧ繧呈ｭｦ蝎ｨ縺ｫ蜈ｷ菴鍋噪謨第ｸ医ｒ謌舌＠驕ゅ￡縺溯ｿ台ｻ｣逵玖ｭｷ縺ｮ豈阪・, avatar: 'assets/nightingale_warhol.png', isPreStyled: true },
  { id: 'yosano', face: 2, pos: 7, name: '荳手ｬ晞㍽譎ｶ蟄・, role: '豁御ｺｺ', homeLocationId: 'graveyard', flavor: '諠・・', color: 'bg-red-900/50', description: '轤弱・繧医≧縺ｪ螳倩・縺ｨ蜿肴姶縺ｮ荳榊ｱ医・蠢・〒縲∫函蜻ｽ縺ｮ霄榊虚繧呈ｭ後＞荳翫￡縺滓ュ辭ｱ縺ｮ譏溘・, avatar: 'assets/yosano_warhol.png', isPreStyled: true },
  { id: 'higuchi', face: 2, pos: 8, name: '讓句哨荳闡・, role: '菴懷ｮｶ', homeLocationId: 'market', flavor: '謔ｲ蜩', color: 'bg-itako-sand', description: '雋ｧ蝗ｰ縺ｨ縺・≧驕朱・縺ｪ迴ｾ螳溘・荳ｭ縺ｧ縲∵凾莉｣縺ｮ遘ｻ繧阪＞縺ｨ鬲ゅ・雋ｴ縺輔ｒ謠上＞縺溘・, avatar: 'assets/higuchi_warhol.png', isPreStyled: true },

  // 笏笏 Face 3: 隘ｿ豢九・鬲・笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏
  { id: 'toynbee', face: 3, pos: 0, name: '繝医う繝ｳ繝薙・', role: '豁ｴ蜿ｲ螳ｶ', homeLocationId: 'library', flavor: '謖第姶', color: 'bg-zinc-700', description: '譁・・縺ｮ闊井ｺ｡繧偵梧倦謌ｦ縺ｨ蠢懈姶縲阪・蜴溽炊縺ｧ隗｣縺肴・縺九＠縺・0荳也ｴ譛螟ｧ縺ｮ豁ｴ蜿ｲ螳ｶ縲・, avatar: 'assets/toynbee_warhol.png', isPreStyled: true },
  { id: 'rand', face: 3, pos: 1, name: '繧｢繧､繝ｳ繝ｻ繝ｩ繝ｳ繝・, role: '蜩ｲ蟄ｦ閠・, homeLocationId: 'throne', flavor: '蜷育炊荳ｻ鄒ｩ', color: 'bg-zinc-700', isMainChar: true, description: '螳｢隕ｳ逧・樟螳溘ｒ逶ｴ隕悶＠縲∝粋逅・噪縺ｪ蛻ｩ蟾ｱ蠢・ｒ閾ｳ鬮倥→縺吶ｋ螳｢隕ｳ荳ｻ鄒ｩ縺ｮ謠仙罰閠・・, avatar: 'assets/rand_warhol.webp', isPreStyled: true },
  { id: 'proudhon', face: 3, pos: 2, name: '繝励Ν繝ｼ繝峨Φ', role: '諤晄Φ螳ｶ', homeLocationId: 'factory', flavor: '逶ｸ莠剃ｸｻ鄒ｩ', color: 'bg-zinc-700', description: '蝗ｽ螳ｶ繧貞凄螳壹＠縲∝ｯｾ遲峨↑莠､謠帙↓蝓ｺ縺･縺冗､ｾ莨夂ｧｩ蠎上ｒ隱ｬ縺・◆逶ｸ莠剃ｸｻ鄒ｩ縺ｮ辷ｶ縲・, avatar: 'assets/proudhon_warhol.png', isPreStyled: true },
  { id: 'socrates', face: 3, pos: 3, name: '繧ｽ繧ｯ繝ｩ繝・せ', role: '蜩ｲ蟄ｦ閠・, homeLocationId: 'oracle', flavor: '蝠冗ｭ・, color: 'bg-itako-sand', description: '蟇ｾ隧ｱ縺ｫ繧医▲縺ｦ遒ｺ險ｼ繧定ｧ｣菴薙＠縲∫悄逅・∈縺ｮ謗｢遨ｶ繧剃ｿ・＠邯壹￠繧玖･ｿ豢句憧蟄ｦ縺ｮ逾悶・, avatar: 'assets/socrates_warhol.png', isPreStyled: true },
  { id: 'descartes', face: 3, pos: 4, name: '繝・き繝ｫ繝・, role: '謨ｰ蟄ｦ閠・・蜩ｲ蟄ｦ閠・, homeLocationId: 'mirror', flavor: '譁ｹ豕・, color: 'bg-zinc-700', description: '譁ｹ豕慕噪諛千桝縲ゅ梧・諤昴≧縲√ｆ縺医↓謌代≠繧翫阪→縺・≧遒ｺ螳溘↑荳轤ｹ縲・, avatar: 'assets/descartes_warhol.png', isPreStyled: true },
  { id: 'spinoza', face: 3, pos: 5, name: '繧ｹ繝斐ヮ繧ｶ', role: '遐皮｣ｨ蟶ｫ', homeLocationId: 'window', flavor: '蠢・┯', color: 'bg-itako-sage', description: '荳・黄繧堤･橸ｼ郁・辟ｶ・峨・蠢・┯諤ｧ縺ｨ縺励※謐峨∴縲∫炊諤ｧ縺ｮ蜈峨〒豌ｸ驕縺ｮ蝟懊・繧呈ｱゅａ縺溘・, avatar: 'assets/spinoza_warhol.png', isPreStyled: true },
  { id: 'hegel', face: 3, pos: 6, name: '繝倥・繧ｲ繝ｫ', role: '蠑∬ｨｼ豕輔・蟾ｨ莠ｺ', homeLocationId: 'tower', flavor: '邊ｾ逾樣ｲ蛹・, color: 'bg-zinc-700', description: '蠑∬ｨｼ豕輔↓繧医ｊ縲∽ｸ也阜繧堤ｵｶ蟇ｾ邊ｾ逾槭・騾ｲ蛹悶・繝励Ο繧ｻ繧ｹ縺ｨ縺励※謐峨∴縺溘・, avatar: 'assets/hegel_warhol.png', isPreStyled: true },
  { id: 'marx', face: 3, pos: 7, name: '繝槭Ν繧ｯ繧ｹ', role: '遉ｾ莨壼ｭｦ閠・, homeLocationId: 'factory', flavor: '讒矩謇ｹ蛻､', color: 'bg-red-900/60', description: '雉・悽荳ｻ鄒ｩ縺ｮ譛ｬ雉ｪ繧偵梧誓蜿悶阪→蝟晉ｴ縺励∵ｭｴ蜿ｲ縺ｮ讒矩逧・､蛾擠繧定ｿｽ豎ゅ・, avatar: 'assets/marx_warhol.png', isPreStyled: true },
  { id: 'freud', face: 3, pos: 8, name: '繝輔Ο繧､繝・, role: '邊ｾ逾槫・譫仙ｮｶ', homeLocationId: 'waiting', flavor: '豺ｱ螻､蠢・炊', color: 'bg-zinc-800', description: '譌･蟶ｸ繧呈髪驟阪☆繧九檎┌諢剰ｭ倥阪・蟄伜惠繧定ｧ｣縺肴・縺九＠縺溽ｲｾ逾槫・譫舌・逋ｺ隕玖・・, avatar: 'assets/freud_warhol.png', isPreStyled: true },
  { id: 'wittgenstein', face: 3, pos: 9, name: '繧ｦ繧｣繝医ご繝ｳ繧ｷ繝･繧ｿ繧､繝ｳ', role: '蟄､鬮倥・諤晄Φ螳ｶ', homeLocationId: 'void', flavor: '髯千阜', color: 'bg-zinc-700', description: '險隱槭・髯千阜繧剃ｸ也阜縺ｮ髯千阜縺ｨ縺励∬ｪ槭ｊ縺医〓繧ゅ・縺ｸ縺ｮ豐磯ｻ吶ｒ隱ｬ縺・◆縲・, avatar: 'assets/wittgenstein_warhol.png', isPreStyled: true },

  // 笏笏 Face 4: 闃ｸ陦灘ｮｶ繝ｻ隧ｩ莠ｺ 笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏
  { id: 'frankl', face: 4, pos: 0, name: '繝輔Λ繝ｳ繧ｯ繝ｫ', role: '邊ｾ逾樒ｧ大現', homeLocationId: 'altar', flavor: '諢丞ｿ・, color: 'bg-orange-950/70', description: '讌ｵ髯千憾諷九〒繧よ・蠎ｦ繧帝∈謚槭☆繧九梧怙蠕後・閾ｪ逕ｱ縲阪ｒ隱ｬ縺・◆諢丞袖縺ｮ蠢・炊蟄ｦ縲・, avatar: 'assets/frankl_warhol.png', isPreStyled: true },
  { id: 'jack_london', face: 4, pos: 1, name: '繧ｸ繝｣繝・け繝ｻ繝ｭ繝ｳ繝峨Φ', role: '菴懷ｮｶ', homeLocationId: 'cliff', flavor: '驥守函', color: 'bg-itako-sand', description: '闕帝㍽縺ｮ螳滉ｽ馴ｨ薙↓蝓ｺ縺･縺阪∫函蜻ｽ縺ｮ辷・匱逧・お繝阪Ν繧ｮ繝ｼ繧定け螳壹・, avatar: 'assets/jack_london_warhol.png', isPreStyled: true },
  { id: 'basho', face: 4, pos: 2, name: '譚ｾ蟆ｾ闃ｭ阨・, role: '菫ｳ莠ｺ', homeLocationId: 'mountain', flavor: '荳肴・豬∬｡・, color: 'bg-itako-sage', description: '荳迸ｬ縺ｮ荳ｭ縺ｫ豌ｸ驕縺ｮ髱吝ｯゅｒ隕句・縺吶よ羅繧剃ｿｮ陦後→縺励◆髫騾ｸ縺ｮ鄒主ｭｦ縲・, avatar: 'assets/basho_warhol.png', isPreStyled: true },
  { id: 'shakespeare', face: 4, pos: 3, name: '繧ｷ繧ｧ繧､繧ｯ繧ｹ繝斐い', role: '蜉・ｽ懷ｮｶ', homeLocationId: 'theatre', flavor: '莠ｺ逕溘・闊槫床', color: 'bg-itako-sand', description: '莠ｺ髢薙・縺ゅｉ繧・ｋ闡幄陸繧定ｨ隱槫喧縺励∬・譛ｬ縺ｫ蛻ｻ繧薙□險闡峨・逾槭・, avatar: 'assets/shakespeare_warhol.png', isPreStyled: true },
  { id: 'beethoven', face: 4, pos: 4, name: '繝吶・繝医・繝ｴ繧ｧ繝ｳ', role: '菴懈峇螳ｶ', homeLocationId: 'roof', flavor: '豁灘万', color: 'bg-zinc-800', description: '驕句多縺ｸ縺ｮ螻域恪繧呈拠蜷ｦ縺励∽ｸ榊ｱ医・髣伜ｿ励〒遨ｶ讌ｵ縺ｮ隱ｿ蜥後ｒ霑ｽ豎ゅ・, avatar: 'assets/beethoven_warhol.png', isPreStyled: true },
  { id: 'chopin', face: 4, pos: 5, name: '繧ｷ繝ｧ繝代Φ', role: '繝斐い繝九せ繝・, homeLocationId: 'piano', flavor: '驛ｷ諢・, color: 'bg-itako-sand', description: '郢顔ｴｰ縺ｪ諞るｬｱ縺ｨ縲∫ｵ先匕蛹悶＠縺溽ｴ皮ｲ九↑謔ｲ縺励∩繧帝浹縺ｫ險励＠縺溘ヴ繧｢繝弱・隧ｩ莠ｺ縲・, avatar: 'assets/chopin_warhol.png', isPreStyled: true },
  { id: 'orwell', face: 4, pos: 6, name: '繧ｸ繝ｧ繝ｼ繧ｸ繝ｻ繧ｪ繝ｼ繧ｦ繧ｧ繝ｫ', role: '逶｣隕冶・, homeLocationId: 'prison', flavor: '逵溷ｮ・, color: 'bg-zinc-700', description: '蜈ｨ菴謎ｸｻ鄒ｩ縺ｮ諱先悶ｒ隴ｦ蜻翫＠縲∬ｨ隱槭・謫堺ｽ懊↓繧医ｋ諤晁・●豁｢繧貞ｿ後∩雖後≧縲・, avatar: 'assets/orwell_warhol.png', isPreStyled: true },
  { id: 'rilke', face: 4, pos: 7, name: '繝ｪ繝ｫ繧ｱ', role: '隧ｩ莠ｺ', homeLocationId: 'tower', flavor: '蟄､迢ｬ', color: 'bg-itako-sand', description: '莠狗黄縺ｮ隕ｳ蟇溘→蟄伜惠縺ｮ蟄､迢ｬ縲ょ､ｱ繧上ｌ繧・￥繧ゅ・繧定ｩｩ縺ｮ荳ｭ縺ｫ謨代＞蜃ｺ縺吶・, avatar: 'assets/rilke_warhol.png', isPreStyled: true },
  { id: 'lu_xun', face: 4, pos: 8, name: '鬲ｯ霑・, role: '諤晄Φ螳ｶ', homeLocationId: 'school', flavor: '隕夐・', color: 'bg-red-950/70', description: '縲碁延縺ｮ驛ｨ螻九阪〒逵繧区ｰ題｡・ｒ逶ｮ隕壹ａ縺輔○繧九◆繧√↓縲∫ｵｶ譛帙・蜿ｫ縺ｳ繧帝ｳｴ繧峨☆縲・, avatar: 'assets/lu_xun_warhol.png', isPreStyled: true },
  { id: 'nyarla', face: 4, pos: 9, name: '繝九Ε繝ｫ繝ｩ繝医・繝・・', role: '豺ｷ豐後・菴ｿ閠・, homeLocationId: 'void', flavor: '荳肴擅逅・, color: 'bg-indigo-950/80', description: '蜊・・蜷榊燕縺ｨ蟋ｿ繧呈戟縺､縲√碁吶＞蟇・ｋ豺ｷ豐後阪ょｺ・ｴ縺ｮ陬ゅ￠逶ｮ縺九ｉ縲√％縺ｮ荳也阜縺ｮ逅・ｒ蝌ｲ隨代≧縲・, avatar: 'assets/nyarla_warhol.png', isPreStyled: true },

  // 笏笏 Face 5: 豁ｴ蜿ｲ縺ｨ螳玲蕗 笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏笏
  { id: 'khaldun', face: 5, pos: 0, name: '繧､繝悶Φ繝ｻ繝上Ν繝峨ぇ繝ｼ繝ｳ', role: '豁ｴ蜿ｲ螳ｶ', homeLocationId: 'library', flavor: '繧｢繧ｵ繝薙・繝､', color: 'bg-amber-950/70', description: '豁ｴ蜿ｲ縺ｮ蜻ｨ譛溷ｾ具ｼ医い繧ｵ繝薙・繝､縺ｮ逶幄｡ｰ・峨ｒ隱ｬ縺冗衍縺ｮ蟾ｨ譏溘ょ・蜷御ｽ薙・蟇ｿ蜻ｽ繧・20蟷ｴ・・650譌･/3荳紋ｻ｣・峨→逵狗ｴ縺励◆縲・, avatar: 'assets/khaldun_warhol.png', isPreStyled: true },
  { id: 'arendt', face: 5, pos: 1, name: '繝上Φ繝翫・繧｢繝ｼ繝ｬ繝ｳ繝・, role: '謾ｿ豐ｻ蜩ｲ蟄ｦ閠・, homeLocationId: 'office', flavor: '螳｢隕ｳ蛻・梵', color: 'bg-zinc-800', description: '縲梧が縺ｮ蜃｡蠎ｸ縺輔阪→讓ｩ蜉帙・讒矩繧貞・蠕ｹ縺ｫ蛻・梵縲よ─諠・ｒ謗偵＠縺溽｡ｬ雉ｪ縺ｪ險隱槭〒逵溷ｮ溘ｒ險倩ｿｰ縺吶ｋ縲・, avatar: 'assets/arendt_warhol.png', isPreStyled: true },
  { id: 'thucydides', face: 5, pos: 2, name: '繝医ぇ繧ｭ繝･繝・ぅ繝・せ', role: '豁ｴ蜿ｲ螳ｶ', homeLocationId: 'waiting', flavor: '讓ｩ蜉帛虚蟄ｦ', color: 'bg-zinc-700', description: '縲取姶蜿ｲ縲上・闡苓・よ＄諤悶∝錐隱峨∝茜逶翫↓繧医ｋ讓ｩ蜉帶ｧ矩縺ｮ荳榊庄騾・噪縺ｪ螟牙喧繧定ｦｳ貂ｬ縺吶ｋ縲・, avatar: 'assets/thucydides_warhol.png', isPreStyled: true },
  { id: 'dogen', face: 5, pos: 3, name: '驕灘・', role: '遖・ｸｫ', homeLocationId: 'temple', flavor: '譛画凾', color: 'bg-zinc-900', description: '縲梧怏譎ゑｼ域凾蛻・√＞縺ｾ縺薙％・峨阪・蜩ｲ蟄ｦ繧定ｪｬ縺上ゆｸ迸ｬ縺梧ｰｸ驕縺ｧ縺ゅｊ縲∽ｸ・黄縺悟ｮ溽嶌縺ｧ縺ゅｋ縺薙→繧呈蕗遉ｺ縺吶・, avatar: 'assets/dogen_warhol.png', isPreStyled: true },
  { id: 'shinran', face: 5, pos: 4, name: '隕ｪ鮑・, role: '髢狗･・, homeLocationId: 'temple', flavor: '諷域・', color: 'bg-zinc-800', isMainChar: true, description: '縲御ｻ門鴨譛ｬ鬘倥阪→縲梧が莠ｺ豁｣讖溘阪よｷｱ縺・ｬ呵劒縺輔→蜈ｱ縺ｫ縲∝・螟ｫ縺ｮ謨第ｸ医ｒ髱吶°縺ｫ蝗√￥縲・, avatar: 'assets/shinran_warhol.png', isPreStyled: true },
  { id: 'ishimure', face: 5, pos: 5, name: '遏ｳ迚溽､ｼ驕灘ｭ・, role: '蟾ｫ螂ｳ逧・ｽ懷ｮｶ', homeLocationId: 'lake', flavor: '繧｢繝九・', color: 'bg-green-950/70', description: '螢ｰ縺ｪ縺崎・◆縺｡縺ｮ螢ｰ繧偵梧じ縺亥刈蜍｢縲阪→縺励※諡ｾ縺・ｸ翫￡縲∫函閠・→豁ｻ閠・・蜈ｱ逕溘ｒ逾医ｋ縲・, avatar: 'assets/ishimure_warhol.png', isPreStyled: true },
  { id: 'orikuchi', face: 5, pos: 6, name: '謚伜哨菫｡螟ｫ', role: '豌台ｿ怜ｭｦ閠・, homeLocationId: 'temple', flavor: '縺ｾ繧後・縺ｨ', color: 'bg-indigo-950/70', description: '縲後∪繧後・縺ｨ縲阪・讎ょｿｵ繧帝壹§縺ｦ譌･譛ｬ莠ｺ縺ｮ邊ｾ逾槭・豺ｱ螻､繧呈垓縺丞商莉｣諢溯ｦ壹・蜀崎・閠・・, avatar: 'assets/orikuchi_shinobu_warhol.png', isPreStyled: true },
  { id: 'shadow', face: 5, pos: 7, name: '蠖ｱ', role: '豺ｱ螻､蠢・炊', homeLocationId: 'underpass', flavor: '謚大悸', color: 'bg-zinc-900', description: '蜷・ｺｺ縺瑚レ雋縺・∫峩隕悶＠縺後◆縺・・蟾ｱ縺ｮ蜊願ｺｫ縲りｪ崎ｭ倥＆繧後〓縺ｾ縺ｾ縲∝ｺ・ｴ縺ｮ髫・↓髱吶°縺ｫ菴・・縲・, avatar: 'assets/shadow_warhol.png', isPreStyled: true },
  { id: 'trickster', face: 5, pos: 8, name: '繝医Μ繝・け繧ｹ繧ｿ繝ｼ', role: '謠ｺ縺輔・繧玖・, homeLocationId: 'well', flavor: '豺ｷ豐・, color: 'bg-orange-950/60', description: '譌｢蟄倥・遘ｩ蠎上ｒ謾ｪ荵ｱ縺励∵眠縺溘↑蜿ｯ閭ｽ諤ｧ繧貞ｭ輔・驕灘喧縲ょ｢・阜邱壹ｒ鬟帙・雜翫∴縲∝●貊槭ｒ謇鍋ｴ縺吶ｋ縲・, avatar: 'assets/trickster_warhol.png', isPreStyled: true },
  { id: 'narrator', face: 5, pos: 9, name: '隱槭ｊ謇・, role: '迚ｩ隱槭・邏｡縺取焔', homeLocationId: 'archive', flavor: '險倬鹸', color: 'bg-zinc-800', description: '縺薙・蠎・ｴ縺ｧ襍ｷ縺阪ｋ蜈ｨ縺ｦ縺ｮ蜃ｺ譚･莠九ｒ縲∬ｷ晞屬繧堤ｽｮ縺・※險倩ｿｰ縺吶ｋ雜・ｶ顔噪縺ｪ螢ｰ縲・, avatar: 'assets/narrator_warhol.png', isPreStyled: true },
];

export const AMBIENT_COLORS = {
  neutral: { color: '#000000', pattern: 'radial-gradient(circle, #111 2px, transparent 2px)' },
  serene: { color: '#051515', pattern: 'radial-gradient(circle at 50% 50%, #0a2a2a 0%, #000 80%)' },
  agitated: { color: '#1a0505', pattern: 'radial-gradient(ellipse at center, #300 0%, transparent 70%)' },
  melancholic: { color: '#0a0a15', pattern: 'linear-gradient(to bottom, #1a2a3a 1px, transparent 1px)' },
  joyful: { color: '#1a1505', pattern: 'radial-gradient(circle, #2a2005 2px, transparent 2px)' },
  chaotic: { color: '#0f0515', pattern: 'repeating-linear-gradient(45deg, #102 0, #102 1px, transparent 0, transparent 20px)' },
};
