export const INITIAL_CHARACTERS = [
  { id: 'soseki', name: '夏目漱石', role: '大学教授', homeLocationId: 'school', flavor: '胃痛', color: 'bg-itako-clay', description: '日本の小説家、英文学者。大学教授としての職務と創作の狭間で胃を病んでいる。', avatar: 'assets/soseki_warhol.png', isPreStyled: true },
  { id: 'dosto', name: 'ドストエフスキー', role: '債務者・作家', homeLocationId: 'casino', flavor: '借金', color: 'bg-itako-sand', description: 'ロシアの文豪。ルーレットへの執着と膨大な借金、そして信仰の間で魂が微振動している。', avatar: 'assets/dosto_warhol.png', isPreStyled: true },
  { id: 'ichikawa', name: '市川房枝', role: '政治家', homeLocationId: 'office', flavor: '厳格', color: 'bg-itako-sage', description: '婦人運動家、参議院議員。政治の浄化と有権者の啓発を、広場でも厳格に説き続ける。', avatar: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Photo-Book-of-Fusae-Ichikawa-11.jpg' },
  { id: 'atsuko', name: 'Atsuko', role: '古本屋の店主', homeLocationId: 'archive_room', flavor: '見守り', color: 'bg-itako-sand', description: '広場の地下深く、崩れかけの書庫で古本を売る。すべてを記録し、観察する不気味な存在。', avatar: 'assets/atsuko_warhol.png', isPreStyled: true },
  { id: 'k_kokoro', name: 'K', role: '無職・書生', homeLocationId: 'stair', flavor: '絶望', color: 'bg-zinc-800', description: 'かつては学生。今はただ絶望の螺旋階段を上り下りする、目的を持たない魂。', avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Japanese_student_c1900.jpg/330px-Japanese_student_c1900.jpg' },
  { id: 'alyosha', name: 'アリョーシャ', role: '修道士', homeLocationId: 'temple', flavor: '信仰', color: 'bg-itako-sage', description: '『カラマーゾフの兄弟』の三男。泥の中でも光を失わず、あらゆる罪を許そうとする。', avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Alyosha_Vanya.jpg/330px-Alyosha_Vanya.jpg' },
  { id: 'raicho', name: '平塚らいてう', role: '思想家', homeLocationId: 'shrine', flavor: '太陽', color: 'bg-orange-900/50', description: '青踏社主宰。元始、女性は太陽であったと宣言した、内なる光を放つ霊。', avatar: 'assets/raicho_warhol.png', isPreStyled: true },
  { id: 'fumiko', name: '金子文子', role: '浮浪・アナキスト', homeLocationId: 'underpass', flavor: '自己', color: 'bg-red-950/60', description: '国家を否定し、ガード下や独房で「自己」の主体性を貫いた。無籍者。', avatar: 'assets/fumiko_warhol.png', isPreStyled: true },
  { id: 'rand', name: 'アイン・ランド', role: '富裕層インタビュアー', homeLocationId: 'throne', flavor: '利己', color: 'bg-zinc-700', description: '客観主義者。成功した強者のみにマイクを向け、弱さという寄生を断罪する。', avatar: 'assets/rand_warhol.png', isPreStyled: true },
];

export const INITIAL_LOCATIONS = [
  { id: 'cafe', name: 'カフェ', face: 0, pos: 0, tags: ['narrow'], description: '微かなコーヒーの香りが生者の執着を思い出させる。', color: '#1a1a1a', pattern: 'radial-gradient(circle, #222 1px, transparent 1px)' },
  { id: 'library', name: '図書館', face: 0, pos: 1, tags: ['quiet'], description: '開かれることのない蔵書たちが、重力のような沈黙を強いている。', color: '#0f141a', pattern: 'linear-gradient(45deg, #ffffff03 25%, transparent 25%)' },
  { id: 'garden', name: '庭園', face: 0, pos: 2, tags: ['wide', 'nature'], description: '枯れない花々。時間はここでは結晶化している。', color: '#0f1a0f', pattern: 'radial-gradient(circle, #1a2a1a 1px, transparent 1px)' },
  { id: 'elevator', name: '昇降機', face: 0, pos: 3, tags: ['narrow'], description: '閉ざされた立方体。目的地のない沈黙。', color: '#111', pattern: 'linear-gradient(to bottom, #222 1px, transparent 1px)' },
  { id: 'park', name: '広い公園', face: 0, pos: 4, tags: ['wide'], description: '空が剥き出しの場所。誰ともすれ違わない散歩道。', color: '#1a2a1a', pattern: 'radial-gradient(circle at 50% 50%, #2a3a2a 20%, transparent 80%)' },
  { id: 'market', name: '市場', face: 0, pos: 5, tags: ['noisy'], description: '物々交換される記憶。中身のない言葉が飛び交う。', color: '#1a150f', pattern: 'repeating-linear-gradient(45deg, #222, #222 2px, transparent 2px, transparent 10px)' },
  { id: 'school', name: '校舎', face: 0, pos: 6, tags: ['quiet'], description: '永遠に終わらない放課後のチャイム。', color: '#151a20', pattern: 'linear-gradient(to bottom, #1a2a3a 1px, transparent 1px)' },
  { id: 'roof', name: '屋上', face: 0, pos: 7, tags: ['wide'], description: 'フェンスの向こう側は、何もない空。', color: '#0a1015', pattern: 'linear-gradient(to bottom, #1a2a3a, transparent)' },
  { id: 'theatre', name: '劇場', face: 0, pos: 8, tags: ['wide'], description: '観客のいない舞台。拍手の残響だけが揺れている。', color: '#1a0505', pattern: 'radial-gradient(ellipse at center, #300 0%, transparent 70%)' },
  { id: 'passage', name: '地下通路', face: 1, pos: 0, tags: ['narrow'], description: 'すべての後悔へと通じている冷たいコンクリートの回廊。', color: '#050505', pattern: 'repeating-linear-gradient(0deg, #111 0, #111 1px, transparent 0, transparent 20px)' },
  { id: 'stair', name: '螺旋階段', face: 1, pos: 1, tags: ['narrow'], description: '上っても下っても、同じ階層に辿り着く。', color: '#0a0a0a', pattern: 'conic-gradient(from 0deg, #111, #000)' },
  { id: 'mirror', name: '鏡の間', face: 1, pos: 2, tags: ['narrow'], description: '自分以外のすべてが映る鏡。', color: '#101015', pattern: 'linear-gradient(135deg, #222 25%, transparent 25%)' },
  { id: 'waiting', name: '待合室', face: 1, pos: 3, tags: ['quiet'], description: 'いつまでも来ない列車を待つ影たち。', color: '#0f0f0f', pattern: 'radial-gradient(circle, #222 2px, transparent 2px)' },
  { id: 'prison', name: '独房', face: 1, pos: 4, tags: ['narrow'], description: '自己との対面を強いる最小限の空間。', color: '#111', pattern: 'none' },
  { id: 'window', name: '額縁の窓', face: 1, pos: 5, tags: ['quiet'], description: '風景を切り取ったまま動かない。', color: '#050a15', pattern: 'linear-gradient(to bottom, #0a1a2a, transparent)' },
  { id: 'door', name: '開かずの扉', face: 1, pos: 6, tags: ['narrow'], description: '鍵のない境界線。向こう側の気配。', color: '#150505', pattern: 'linear-gradient(to right, #200, transparent)' },
  { id: 'box', name: '暗室', face: 1, pos: 7, tags: ['narrow'], description: '意識だけが漂う暗闇。', color: '#000', pattern: 'none' },
  { id: 'archive_room', name: '地下書庫', face: 1, pos: 8, tags: ['quiet'], description: '湿った紙の断片が、誰かの一生を黙殺している。', color: '#0a0505', pattern: 'repeating-linear-gradient(0deg, #211, #000 2px)' },
  { id: 'shrine', name: '神社', face: 2, pos: 0, tags: ['quiet'], description: '形なき祈りだけが風に震えている。', color: '#1a0f0f', pattern: 'radial-gradient(circle, #300 2px, transparent 2px)' },
  { id: 'altar', name: '祭壇', face: 2, pos: 1, tags: ['quiet'], description: '供えられたのは、名もなき者の悔恨。', color: '#150f15', pattern: 'radial-gradient(circle at 50% 50%, #202, transparent)' },
  { id: 'temple', name: '寺院', face: 2, pos: 2, tags: ['wide'], description: '鐘の音は空へは昇らず、地へと染み込む。', color: '#0f0f05', pattern: 'repeating-conic-gradient(#110 0deg 10deg, #000 10deg 20deg)' },
  { id: 'forest', name: '鎮守の森', face: 2, pos: 3, tags: ['nature', 'wide'], description: '木々の隙間に、誰かの瞳が光る。', color: '#051005', pattern: 'radial-gradient(circle, #020 3px, transparent 3px)' },
  { id: 'lake', name: '静かな湖', face: 2, pos: 4, tags: ['wide', 'nature'], description: '波紋のない水面。深淵の入口。', color: '#0a1a1a', pattern: 'radial-gradient(ellipse at center, #0a2a2a 0%, #000 70%)' },
  { id: 'mountain', name: '虚無山', face: 2, pos: 5, tags: ['wide', 'nature'], description: '道のない山。登るほどに自分を失う。', color: '#1a1005', pattern: 'linear-gradient(to top, #210, transparent)' },
  { id: 'graveyard', name: '墓地', face: 2, pos: 6, tags: ['quiet'], description: '名前が削れた石碑。死者さえ忘れた墓。', color: '#0a0f0a', pattern: 'radial-gradient(circle, #121 1px, transparent 1px)' },
  { id: 'tower', name: '五重塔', face: 2, pos: 7, tags: ['narrow'], description: '天への梯子。途中で途切れている。', color: '#1a1005', pattern: 'linear-gradient(to top, #210, transparent)' },
  { id: 'cliff', name: '断崖', face: 2, pos: 8, tags: ['nature'], description: 'ここから先は、言葉のない領域。', color: '#0a0a0a', pattern: 'linear-gradient(to top, #111, transparent)' },
  { id: 'backalley', name: '路地裏', face: 3, pos: 0, tags: ['narrow'], description: '捨てられた概念が腐敗している。', color: '#0a0a0a', pattern: 'radial-gradient(circle, #1a1a1a 1px, transparent 1px)' },
  { id: 'casino', name: '賽の河原賭博場', face: 3, pos: 1, tags: ['gambling', 'narrow'], description: '魂を賭けてサイコロを振る、終わりのない遊戯。', color: '#1a0505', pattern: 'radial-gradient(circle at center, #300 0%, #000 80%)' },
  { id: 'neon', name: 'ネオン街', face: 3, pos: 2, tags: ['noisy'], description: '電圧の低い欲望。明滅する幽霊文字。', color: '#0a051a', pattern: 'linear-gradient(90deg, #102 1px, transparent 1px)' },
  { id: 'junkyard', name: '廃材置場', face: 3, pos: 3, tags: ['wide'], description: '意味を失った機械たちの、冷たい囁き。', color: '#1a1a1a', pattern: 'repeating-linear-gradient(45deg, #222, #000 5px)' },
  { id: 'underpass', name: 'ガード下', face: 3, pos: 4, tags: ['narrow'], description: '絶え間ない振動。誰の足音でもない。', color: '#050505', pattern: 'linear-gradient(transparent 50%, #111 50%)' },
  { id: 'slum', name: '裏通りの吹き溜まり', face: 3, pos: 5, tags: ['narrow'], description: '希望が廃棄された場所。', color: '#1a0a05', pattern: 'none' },
  { id: 'canal', name: '運河', face: 3, pos: 6, tags: ['wide'], description: 'オイルの浮いた水面が、偽物の月を映す。', color: '#051010', pattern: 'radial-gradient(circle at 10% 10%, #122, transparent)' },
  { id: 'port', name: '亡霊の港', face: 3, pos: 7, tags: ['wide'], description: '出航しない船だけが繋がれている。', color: '#0a1015', pattern: 'none' },
  { id: 'factory', name: '廃工場', face: 3, pos: 8, tags: ['wide'], description: 'リズムだけが生き続ける、主のいない生産ライン。', color: '#111', pattern: 'repeating-linear-gradient(90deg, #222 0, #222 2px, transparent 0, transparent 40px)' },
  { id: 'bridge', name: '橋', face: 4, pos: 0, tags: ['wide'], description: '過去の記憶をどこか遠くへ運んでいく。', color: '#0f1a1a', pattern: 'linear-gradient(to right, #ffffff05 1px, transparent 1px)' },
  { id: 'station', name: '無人駅', face: 4, pos: 1, tags: ['wide'], description: '改札口を通る者は、もう誰もいない。', color: '#151515', pattern: 'repeating-linear-gradient(90deg, #222, #222 1px, transparent 1px, transparent 50px)' },
  { id: 'pier', name: '桟橋', face: 4, pos: 2, tags: ['narrow'], description: '霧の向こうから、呼び聲が聞こえる。', color: '#101520', pattern: 'radial-gradient(circle, #1a2030 1px, transparent 1px)' },
  { id: 'sea', name: '亡霊の海', face: 4, pos: 3, tags: ['wide', 'nature'], description: '岸のない海。記憶が塩分となって溶けている。', color: '#050a15', pattern: 'radial-gradient(ellipse at 50% 100%, #0a2a4a 0%, #000 80%)' },
  { id: 'lighthouse', name: '灯台', face: 4, pos: 4, tags: ['narrow'], description: '光は魂を導かず、ただ闇を薙ぎ払う。', color: '#1a1a05', pattern: 'conic-gradient(from 180deg at 50% 0%, #331, transparent)' },
  { id: 'beach', name: '砂浜', face: 4, pos: 5, tags: ['wide', 'nature'], description: '打ち寄せられるのは、漂流した未練。', color: '#1a1a15', pattern: 'radial-gradient(ellipse, #222, transparent)' },
  { id: 'island', name: '浮島', face: 4, pos: 6, tags: ['nature'], description: '根を持たない地。浮遊する虚無。', color: '#101010', pattern: 'radial-gradient(circle, #222, transparent 50%)' },
  { id: 'ship', name: '難破船', face: 4, pos: 7, tags: ['narrow'], description: '沈みきれないまま漂う後悔の船体。', color: '#0a0a0a', pattern: 'none' },
  { id: 'bottom', name: '海底', face: 4, pos: 8, tags: ['wide', 'quiet'], description: 'すべての音が光と共に消え去る場所。', color: '#000510', pattern: 'none' },
  { id: 'core', name: '核', face: 5, pos: 0, tags: ['narrow'], description: 'すべての魂が収束し、消失する点。', color: '#000000', pattern: 'radial-gradient(circle, #111 2px, transparent 2px)' },
  { id: 'monolith', name: '方尖柱', face: 5, pos: 1, tags: ['narrow'], description: '天を貫く垂直の意志。文字が刻まれている。', color: '#050505', pattern: 'linear-gradient(to right, #1a1a1a, transparent)' },
  { id: 'oracle', name: '神託所', face: 5, pos: 2, tags: ['quiet'], description: '返ってくるのは自分の声だけ。', color: '#050a0a', pattern: 'radial-gradient(circle, #122 1px, transparent 1px)' },
  { id: 'void', name: '虚無', face: 5, pos: 3, tags: ['wide'], description: '色も音も、名前も。すべてが許されない場所。', color: '#000000', pattern: 'none' },
  { id: 'archive', name: '終焉書庫', face: 5, pos: 4, tags: ['quiet'], description: '宇宙の終わりの一秒前まで記された記録。', color: '#0a0505', pattern: 'repeating-linear-gradient(0deg, #211, #000 2px)' },
  { id: 'gate', name: '門', face: 5, pos: 5, tags: ['narrow'], description: '本当の出口か、あるいは永遠の入り口か。', color: '#000000', pattern: 'linear-gradient(45deg, #111 25%, transparent 25%)' },
  { id: 'throne', name: '空の玉座', face: 5, pos: 6, tags: ['wide'], description: '支配なき支配者が坐る、絶対的な不在。', color: '#050505', pattern: 'none' },
  { id: 'mirror_abyss', name: '深淵の鏡', face: 5, pos: 7, tags: ['narrow'], description: '覗き込む時、向こう側もあなたを見ている。', color: '#000', pattern: 'radial-gradient(circle at center, #111, transparent)' },
  { id: 'end', name: '終焉', face: 5, pos: 8, tags: ['wide'], description: 'すべてが完了し、新たな静止が始まる。', color: '#111', pattern: 'none' },
];
